name: Deploy API
on:
  push:
    branches:
      - main


jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          cli_config_credentials_hostname: 'app.staging.terraform.io'
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: Execute Terraform Apply
        run: |
          terraform init
          terraform apply -auto-approve -input=false

      - name: Fetch API GW URL
        id: url
        run: terraform output -raw base_url

      - name: Test endpoint
        run: |
          curl -sSf "${{steps.url.outputs.stdout}}/params?Name=luces"



