name: Deploy API
on:
  push:
    branches:
      - main


jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          cli_config_credentials_hostname: 'app.staging.terraform.io'
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: Execute Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          terraform init
          terraform apply -auto-approve -input=false

      - name: Test endpoint
        run: |
          curl "$(terraform output -raw base_url)/params?Name=luces"



